name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build and test with Docker
        run: |
          docker build --tag sync_conda_environments .
          docker run --rm sync_conda_environments pytest /app
