name: Tests

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Run tests with Miniconda installation on MacOS
        run: |
          # Install miniconda, add it to path.
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh
          bash ~/miniconda.sh -b -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"

          # Install dependencies with poetry.
          pip install poetry
          poetry install

          # Run tests.
          poetry run pytest
